# -*- coding: utf-8 -*-
"""LangchainAgents2026.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s8c0Na-nE6vpTRv8H4XhUEDVDT3ZFLFj
"""
# pip install -U langchain langchain-community  langchain-openai ddgs

import os
from langchain_openai import ChatOpenAI
from langchain_community.tools import DuckDuckGoSearchRun
from langchain.agents import create_agent

import langchain
print(langchain.__version__)

# 1️⃣ LLM
VLLM_BASE_URL = "http://192.168.51.102:8000/v1"
VLLM_API_KEY = "not-needed"          # vLLM ignores this unless launched with --api-key
MODEL = "openai/gpt-oss-120b"

# LLM
llm = ChatOpenAI(
    model=MODEL,
    temperature=0,
    base_url=VLLM_BASE_URL,
    api_key=VLLM_API_KEY,
)

# 2️⃣ Tool
search = DuckDuckGoSearchRun()

# 3️⃣ Create agent (NEW v1 API)
agent = create_agent(
    model=llm,
    tools=[search],
    system_prompt="You are a helpful assistant. You have to use the suitable tools as needed to answer user questions"
)

# 4️⃣ Invoke directly
response = agent.invoke(
    {"messages": [{"role": "user", "content": "What is the latest telecom billing dispute news?"}]}
)

print(response["messages"][-1].content)

import os
import math
from langchain.agents import create_agent
from langchain.tools import tool
from langchain_openai import ChatOpenAI

# 1️⃣ Define Calculator Tool
@tool
def calculator(expression: str) -> str:
    """
    Evaluate a mathematical expression.
    Supports +, -, *, /, %, **, and parentheses.
    Example: 12345 * (67 + 89)
    """
    try:
        # Safe evaluation context
        allowed_names = {
            "math": math
        }
        result = eval(expression, {"__builtins__": {}}, allowed_names)
        return str(result)
    except Exception as e:
        return f"Error: {str(e)}"

# 2️⃣ Create Agent
agent = create_agent(
    model=llm,
    tools=[calculator],
    system_prompt="You are a helpful math assistant. Use the calculator tool for any math computation."
)

# 3️⃣ Invoke Agent
response = agent.invoke(
    {
        "messages": [
            {"role": "user", "content": "What is 12345 * (67 + 89)?"}
        ]
    }
)

print(response["messages"][-1].content)

def emi_calculator(principal: float, annual_interest_rate: float, duration_months: int):
    """
    Calculate EMI and monthly interest rate.

    Args:
        principal (float): Loan amount
        annual_interest_rate (float): Annual interest rate in percentage
        duration_months (int): Loan duration in months

    Returns:
        dict: EMI details
    """

    # Convert annual interest rate to monthly decimal rate
    monthly_rate = annual_interest_rate / 12 / 100

    # EMI Formula
    emi = principal * monthly_rate * (1 + monthly_rate) ** duration_months \
          / ((1 + monthly_rate) ** duration_months - 1)

    return {
        "Principal": principal,
        "Annual Interest Rate (%)": annual_interest_rate,
        "Monthly Interest Rate": round(monthly_rate, 6),
        "Duration (Months)": duration_months,
        "Monthly EMI": round(emi, 2)
    }

# Example usage
result = emi_calculator(500000, 8.5, 60)
print(result)

# 2️⃣ Create Agent
emi_agent = create_agent(
    model=llm,
    tools=[emi_calculator],
    system_prompt="You are a helpful math assistant. The emi_calculator tool helps to compute the emi for a loan with principle, interest rate and loan tenure are inputs and returns the monthly EMI applicable."
)

# 3️⃣ Invoke EMI Agent
response = emi_agent.invoke(
    {
        "messages": [
            {"role": "user", "content": "I am going to get a house which requires 50 lakhs, I have only 10 lakhs in my hand and I have a salary of 1 lakh, can I afford to buy this house and bank is charging 12 percent interest and my laon duration is 10 years?"}
        ]
    }
)
print(response["messages"][-1].content)