# -*- coding: utf-8 -*-
"""RAG_Openai.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g8qkneP7AD7PGyZ0obfWFghPjBZy7HkP
"""
from langchain_community.document_loaders import PyPDFLoader

loader = PyPDFLoader("EC-Council-University-catalog.pdf")   # your PDF
documents = loader.load()

documents[0] .page_content
documents[0] .metadata

from langchain_text_splitters import RecursiveCharacterTextSplitter

text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=800,
    chunk_overlap=150,
    separators=["\n\n", "\n", ".", " ", ""]
)

chunks = text_splitter.split_documents(documents)
print(len(chunks))

from langchain_community.vectorstores import Chroma
from langchain_huggingface import HuggingFaceEmbeddings

embedding_model = HuggingFaceEmbeddings(
    model_name="sentence-transformers/all-MiniLM-L6-v2",
    encode_kwargs={"normalize_embeddings": True},
)
vectorstore = Chroma.from_documents(
    documents=chunks,
    embedding=embedding_model,
    persist_directory="./pdf_rag_db"
)

retriever = vectorstore.as_retriever(
    search_type="similarity",
    search_kwargs={"k": 8}
)

from langchain_openai import ChatOpenAI
from langchain_core.prompts import PromptTemplate

# Local vLLM endpoint (OpenAI-compatible /v1)
VLLM_BASE_URL = "http://192.168.51.100:8000/v1"
VLLM_API_KEY = "not-needed"          # vLLM ignores this unless launched with --api-key
MODEL = "openai/gpt-oss-120b"

# LLM
llm = ChatOpenAI(
    model=MODEL,
    temperature=0,
    base_url=VLLM_BASE_URL,
    api_key=VLLM_API_KEY,
)
query_rewrite_prompt = PromptTemplate(
    input_variables=["question"],
    template="""
Rewrite the user question to be optimal for semantic document retrieval.
Keep it concise and specific.

Original question:
{question}

Rewritten query:
"""
)

def rewrite_query(question):
    return llm.invoke(
        query_rewrite_prompt.format(question=question)
    ).content

rerank_prompt = PromptTemplate(
    input_variables=["question", "documents"],
    template="""
Given the question and retrieved documents, rank the documents by relevance.
Return only the most relevant content.

Question:
{question}

Documents:
{documents}

Relevant content:
"""
)

def rerank(question, docs):
    docs_text = "\n\n".join(d.page_content for d in docs)
    response = llm.invoke(
        rerank_prompt.format(
            question=question,
            documents=docs_text
        )
    )
    return response.content

answer_prompt = PromptTemplate(
    input_variables=["context", "question"],
    template="""
You are a helpful assistant.
Answer the question using ONLY the context below.

Context:
{context}

Question:
{question}

Answer:
"""
)

def generate_answer(question, context):
    response = llm.invoke(
        answer_prompt.format(
            context=context,
            question=question
        )
    )
    return response.content

def pdf_chatbot(question):
    # 1. Rewrite query
    rewritten_query = rewrite_query(question)

    # 2. Retrieve docs
    retrieved_docs = retriever.invoke(rewritten_query)

    # 3. Re-rank
    ranked_context = rerank(question, retrieved_docs)

    # 4. Generate answer
    answer = generate_answer(question, ranked_context)

    return answer

question = "What are the key couorses mentioned?"
response = pdf_chatbot(question)
print(response)